// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Soporte FinFlow",
            "email": "soporte@finflow.dev"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/google": {
            "post": {
                "description": "Autentica al usuario usando un id_token de Google OAuth.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Iniciar sesión con Google",
                "parameters": [
                    {
                        "description": "Token de Google",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.GoogleLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login exitoso",
                        "schema": {
                            "$ref": "#/definitions/domain.AuthResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "Autentica al usuario usando correo y contraseña cifrada por RSA, emitiendo un token JWT.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Iniciar sesión",
                "parameters": [
                    {
                        "description": "Credenciales de acceso",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login exitoso",
                        "schema": {
                            "$ref": "#/definitions/domain.AuthResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/public-key": {
            "get": {
                "description": "Obtiene la clave pública RSA en formato PEM para cifrar contraseñas antes de enviarlas.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Obtener clave pública RSA",
                "responses": {
                    "200": {
                        "description": "Clave pública obtenida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "description": "Crea una cuenta de usuario con correo, contraseña cifrada por RSA y validación de código OTP.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Registrar un usuario",
                "parameters": [
                    {
                        "description": "Datos de registro",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Registro exitoso",
                        "schema": {
                            "$ref": "#/definitions/domain.AuthResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/accounts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene la lista de todas las cuentas del usuario con sus balances. Admite incluir eliminadas lógicamente.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Listar cuentas",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Incluir cuentas eliminadas en papelera",
                        "name": "trashed",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de cuentas obtenida",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Account"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea una nueva cuenta (wallet) asociada al usuario autenticado.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Crear cuenta",
                "parameters": [
                    {
                        "description": "Datos de la cuenta",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cuenta creada correctamente",
                        "schema": {
                            "$ref": "#/definitions/domain.Account"
                        }
                    }
                }
            }
        },
        "/api/v1/accounts/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene la información y el balance calculado de una cuenta del usuario.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Obtener una cuenta",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la cuenta",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cuenta obtenida",
                        "schema": {
                            "$ref": "#/definitions/domain.Account"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza campos específicos de una cuenta existente.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Actualizar cuenta",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la cuenta",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Campos a actualizar",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cuenta actualizada correctamente",
                        "schema": {
                            "$ref": "#/definitions/domain.Account"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mueve la cuenta a la papelera (soft-delete).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Eliminar cuenta (Lógico)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la cuenta",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cuenta eliminada correctamente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/accounts/{id}/permanent": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina de forma física y permanente una cuenta del usuario.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Eliminar cuenta (Permanente)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la cuenta",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cuenta eliminada permanentemente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/accounts/{id}/restore": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Restaura una cuenta que fue eliminada lógicamente y estaba en la papelera.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Restaurar cuenta",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la cuenta",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cuenta restaurada correctamente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/analytics/by-category": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene el listado de gastos o ingresos agrupado por categoría, con montos y porcentajes de participación.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Analíticas por categoría",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fecha desde (YYYY-MM-DD o RFC3339)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fecha hasta (YYYY-MM-DD o RFC3339)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar tipo de transacción (income|expense)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Analíticas obtenidas",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.CategoryAnalytics"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revoca el token de sesión actual en el backend.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Cerrar sesión",
                "responses": {
                    "200": {
                        "description": "Sesión cerrada",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/otp/request": {
            "post": {
                "description": "Envía un código OTP de 6 dígitos al correo electrónico del usuario para REGISTER o RECOVER.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Solicitar código OTP por email",
                "parameters": [
                    {
                        "description": "Datos de la solicitud de OTP",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.OTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Código enviado",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/password/reset": {
            "post": {
                "description": "Restablece la contraseña de acceso consumiendo un código OTP de tipo RECOVER.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Restablecer contraseña con OTP",
                "parameters": [
                    {
                        "description": "Datos de restablecimiento",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Contraseña restablecida",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/budgets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene todos los presupuestos con los totales gastados (spent) y restantes (remaining) en el periodo.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budgets"
                ],
                "summary": "Listar presupuestos",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Incluir presupuestos eliminados",
                        "name": "trashed",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de presupuestos obtenida",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.BudgetWithSpent"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea un nuevo presupuesto (semanal/mensual/anual) para una categoría o global.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budgets"
                ],
                "summary": "Crear presupuesto",
                "parameters": [
                    {
                        "description": "Datos del presupuesto",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateBudgetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Presupuesto creado correctamente",
                        "schema": {
                            "$ref": "#/definitions/domain.Budget"
                        }
                    }
                }
            }
        },
        "/api/v1/budgets/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza el monto, periodo o categoría de un presupuesto.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budgets"
                ],
                "summary": "Actualizar presupuesto",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del presupuesto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos a actualizar",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateBudgetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Presupuesto actualizado correctamente",
                        "schema": {
                            "$ref": "#/definitions/domain.Budget"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina de forma lógica un presupuesto (soft-delete).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budgets"
                ],
                "summary": "Eliminar presupuesto (Lógico)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del presupuesto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Presupuesto eliminado correctamente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/budgets/{id}/permanent": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina de forma física y permanente un presupuesto.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budgets"
                ],
                "summary": "Eliminar presupuesto (Permanente)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del presupuesto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Presupuesto eliminado permanentemente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/budgets/{id}/restore": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Restaura un presupuesto eliminado lógicamente.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budgets"
                ],
                "summary": "Restaurar presupuesto",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del presupuesto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Presupuesto restaurado correctamente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/categories": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene las categorías de ingresos/gastos del usuario. Permite filtrar por tipo e incluir eliminadas.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Listar categorías",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filtrar por tipo (income|expense)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Incluir categorías en papelera",
                        "name": "trashed",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de categorías obtenida",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Category"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea una nueva categoría (ingreso/gasto) para el usuario autenticado.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Crear categoría",
                "parameters": [
                    {
                        "description": "Datos de la categoría",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Categoría creada correctamente",
                        "schema": {
                            "$ref": "#/definitions/domain.Category"
                        }
                    }
                }
            }
        },
        "/api/v1/categories/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza campos de una categoría (nombre, tipo, color, icono).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Actualizar categoría",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la categoría",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos a actualizar",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Categoría actualizada correctamente",
                        "schema": {
                            "$ref": "#/definitions/domain.Category"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mueve la categoría a la papelera (soft-delete).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Eliminar categoría (Lógico)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la categoría",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Categoría eliminada correctamente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/categories/{id}/permanent": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina de forma física y permanente una categoría del usuario.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Eliminar categoría (Permanente)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la categoría",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Categoría eliminada permanentemente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/categories/{id}/restore": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Restaura una categoría eliminada lógicamente.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Restaurar categoría",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la categoría",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Categoría restaurada correctamente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/debts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene todas las deudas del usuario. Permite filtrar por dirección (receivable/payable) y estado de pago.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Debts"
                ],
                "summary": "Listar deudas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dirección de la deuda (receivable|payable)",
                        "name": "direction",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filtrar por pagada (true|false)",
                        "name": "paid",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Incluir deudas eliminadas",
                        "name": "trashed",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de deudas obtenida",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Debt"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registra una nueva deuda (por pagar o por cobrar) con una persona.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Debts"
                ],
                "summary": "Registrar deuda",
                "parameters": [
                    {
                        "description": "Datos de la deuda",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateDebtRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deuda registrada correctamente",
                        "schema": {
                            "$ref": "#/definitions/domain.Debt"
                        }
                    }
                }
            }
        },
        "/api/v1/debts/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene los detalles de una deuda del usuario.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Debts"
                ],
                "summary": "Obtener una deuda",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la deuda",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deuda obtenida",
                        "schema": {
                            "$ref": "#/definitions/domain.Debt"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza campos de una deuda específica.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Debts"
                ],
                "summary": "Actualizar deuda",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la deuda",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos a actualizar",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateDebtRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deuda actualizada correctamente",
                        "schema": {
                            "$ref": "#/definitions/domain.Debt"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina de forma lógica una deuda (soft-delete).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Debts"
                ],
                "summary": "Eliminar deuda (Lógico)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la deuda",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deuda eliminada correctamente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/debts/{id}/pay": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Marca una deuda como liquidada (is_paid: true, paid_at: ahora).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Debts"
                ],
                "summary": "Pagar deuda",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la deuda",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deuda marcada como pagada correctamente",
                        "schema": {
                            "$ref": "#/definitions/domain.Debt"
                        }
                    }
                }
            }
        },
        "/api/v1/debts/{id}/permanent": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina de forma física y permanente una deuda de la base de datos.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Debts"
                ],
                "summary": "Eliminar deuda (Permanente)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la deuda",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deuda eliminada permanentemente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/debts/{id}/restore": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Restaura una deuda eliminada lógicamente.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Debts"
                ],
                "summary": "Restaurar deuda",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la deuda",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deuda restaurada correctamente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/devices": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registra un dispositivo (android/ios/web) y su token push para notificaciones.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Registrar dispositivo",
                "parameters": [
                    {
                        "description": "Datos del dispositivo",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.RegisterDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dispositivo registrado correctamente",
                        "schema": {
                            "$ref": "#/definitions/domain.Device"
                        }
                    }
                }
            }
        },
        "/api/v1/devices/{token}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina el registro del dispositivo para dejar de enviarle notificaciones.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Eliminar dispositivo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token del dispositivo",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dispositivo eliminado correctamente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene los datos del usuario autenticado a partir del token JWT.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Obtener perfil del usuario",
                "responses": {
                    "200": {
                        "description": "Perfil obtenido",
                        "schema": {
                            "$ref": "#/definitions/api.userResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza campos opcionales del perfil del usuario (nombre, avatar, moneda, idioma, tema).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Actualizar perfil del usuario",
                "parameters": [
                    {
                        "description": "Datos de actualización",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Perfil actualizado",
                        "schema": {
                            "$ref": "#/definitions/api.userResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/notifications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene las notificaciones del usuario con soporte de paginación.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Listar notificaciones",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Límite de paginación (defecto 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset de paginación (defecto 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de notificaciones obtenida",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Notification"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/notifications/read-all": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Marca todas las notificaciones de la bandeja del usuario como leídas.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Marcar todas las notificaciones como leídas",
                "responses": {
                    "200": {
                        "description": "Todas leídas",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/notifications/test-push": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Envía una notificación push de prueba a todos los dispositivos del usuario actual.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Enviar push de prueba",
                "parameters": [
                    {
                        "description": "Datos de la notificación de prueba",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.TestPushRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Notificación creada y enviada",
                        "schema": {
                            "$ref": "#/definitions/domain.Notification"
                        }
                    }
                }
            }
        },
        "/api/v1/notifications/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina de forma física una notificación de la bandeja del usuario.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Eliminar notificación",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la notificación",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Notificación eliminada correctamente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/notifications/{id}/read": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Marca una notificación específica de la bandeja del usuario como leída.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Marcar notificación como leída",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la notificación",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Notificación leída",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/transactions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene la lista de transacciones aplicando filtros opcionales (fechas, cuentas, categorías, texto).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Listar transacciones",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fecha desde (YYYY-MM-DD o RFC3339)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fecha hasta (YYYY-MM-DD o RFC3339)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por tipo (income|expense)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID de la categoría",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID de la cuenta",
                        "name": "account_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Búsqueda por descripción (trigram search)",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Incluir transacciones eliminadas lógicamente",
                        "name": "trashed",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Límite de paginación (defecto 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset de paginación (defecto 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de transacciones obtenida",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Transaction"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registra un nuevo ingreso o gasto. Valida que la cuenta y categoría pertenezcan al usuario.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Registrar transacción",
                "parameters": [
                    {
                        "description": "Datos de la transacción",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transacción registrada correctamente",
                        "schema": {
                            "$ref": "#/definitions/domain.Transaction"
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/summary": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene el total de ingresos, gastos, balance y cantidad de transacciones del usuario en un rango de fechas.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Resumen financiero",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fecha desde (YYYY-MM-DD o RFC3339)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fecha hasta (YYYY-MM-DD o RFC3339)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Resumen de transacciones obtenido",
                        "schema": {
                            "$ref": "#/definitions/domain.TransactionSummary"
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtiene los detalles de una transacción del usuario.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Obtener una transacción",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la transacción",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transacción obtenida",
                        "schema": {
                            "$ref": "#/definitions/domain.Transaction"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza campos específicos de una transacción.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Actualizar transacción",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la transacción",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Campos a actualizar",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transacción actualizada correctamente",
                        "schema": {
                            "$ref": "#/definitions/domain.Transaction"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina de forma lógica una transacción (soft-delete).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Eliminar transacción (Lógico)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la transacción",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transacción eliminada correctamente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/{id}/permanent": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina físicamente una transacción de la base de datos.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Eliminar transacción (Permanente)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la transacción",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transacción eliminada permanentemente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/{id}/restore": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Restaura una transacción eliminada lógicamente.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Restaurar transacción",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la transacción",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transacción restaurada correctamente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.TestPushRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "api.userResponse": {
            "type": "object",
            "properties": {
                "auth_provider": {
                    "type": "string"
                },
                "avatar_url": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "email_verified": {
                    "type": "boolean"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "preferred_currency": {
                    "type": "string"
                },
                "preferred_language": {
                    "type": "string"
                },
                "theme_preference": {
                    "type": "string"
                }
            }
        },
        "domain.Account": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number"
                },
                "color": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "icon_key": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "domain.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "domain.Budget": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "category_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "period": {
                    "description": "weekly | monthly | yearly",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "domain.BudgetWithSpent": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "category_color": {
                    "type": "string"
                },
                "category_icon": {
                    "type": "string"
                },
                "category_id": {
                    "type": "integer"
                },
                "category_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "period": {
                    "description": "weekly | monthly | yearly",
                    "type": "string"
                },
                "remaining": {
                    "type": "number"
                },
                "spent": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "domain.Category": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "icon_key": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "domain.CategoryAnalytics": {
            "type": "object",
            "properties": {
                "category_color": {
                    "type": "string"
                },
                "category_icon": {
                    "type": "string"
                },
                "category_id": {
                    "type": "integer"
                },
                "category_name": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "percentage": {
                    "type": "number"
                },
                "total": {
                    "type": "number"
                }
            }
        },
        "domain.CreateAccountRequest": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "icon_key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.CreateBudgetRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "category_id": {
                    "type": "integer"
                },
                "currency": {
                    "type": "string"
                },
                "period": {
                    "type": "string"
                }
            }
        },
        "domain.CreateCategoryRequest": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "icon_key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.CreateDebtRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "currency": {
                    "type": "string"
                },
                "date": {
                    "description": "RFC3339 format",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "direction": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "person_name": {
                    "type": "string"
                }
            }
        },
        "domain.CreateTransactionRequest": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer"
                },
                "amount": {
                    "type": "number"
                },
                "category_id": {
                    "type": "integer"
                },
                "currency": {
                    "type": "string"
                },
                "date": {
                    "description": "RFC3339 format",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.Debt": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "direction": {
                    "description": "receivable | payable",
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_paid": {
                    "type": "boolean"
                },
                "paid_at": {
                    "type": "string"
                },
                "person_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "domain.Device": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "platform": {
                    "description": "android | ios | web",
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "domain.GoogleLoginRequest": {
            "type": "object",
            "properties": {
                "id_token": {
                    "type": "string"
                }
            }
        },
        "domain.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "domain.Notification": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "payload": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "read_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "description": "debt_due | budget_exceeded | system",
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "domain.OTPRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "REGISTER | RECOVER",
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "domain.RegisterDeviceRequest": {
            "type": "object",
            "properties": {
                "platform": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "domain.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "otp_code": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "domain.ResetPasswordRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "new_password": {
                    "description": "cifrada (RSA base64)",
                    "type": "string"
                },
                "otp_code": {
                    "type": "string"
                }
            }
        },
        "domain.Transaction": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer"
                },
                "amount": {
                    "type": "number"
                },
                "category_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "type": {
                    "description": "income | expense",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "domain.TransactionSummary": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number"
                },
                "count": {
                    "type": "integer"
                },
                "total_expense": {
                    "type": "number"
                },
                "total_income": {
                    "type": "number"
                }
            }
        },
        "domain.UpdateAccountRequest": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "icon_key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.UpdateBudgetRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "category_id": {
                    "type": "integer"
                },
                "currency": {
                    "type": "string"
                },
                "period": {
                    "type": "string"
                }
            }
        },
        "domain.UpdateCategoryRequest": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "icon_key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.UpdateDebtRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "currency": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "direction": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "person_name": {
                    "type": "string"
                }
            }
        },
        "domain.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "preferred_currency": {
                    "type": "string"
                },
                "preferred_language": {
                    "type": "string"
                },
                "theme_preference": {
                    "type": "string"
                }
            }
        },
        "domain.UpdateTransactionRequest": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer"
                },
                "amount": {
                    "type": "number"
                },
                "category_id": {
                    "type": "integer"
                },
                "currency": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Escribe: \"Bearer \u003ctoken\u003e\" para autenticarte",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "FinFlow API",
	Description:      "API de FinFlow (Clean Architecture) para control financiero personal y familiar.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
